### ISSUE TITLE
Unable to import H5Sleapdata --- run into a bug

### ISSUE THREAD

**Issue by sara-xinyue-liang** [sgoldenlab/simba#475]
**Describe the bug**
Hi, I recently installed simba in a new device (Macbook Apple M2 Pro, macOS Sequoia 15.6.1) with the newest version 3.8.8. But when I was trying to import the tracking files (Sleap H5), it ran into a bug and get stuck at the first file in where the screenshot shows. 

<img width="804" height="819" alt="Image" src="https://github.com/user-attachments/assets/86546295-ada8-4c17-a8c9-ae253b99fb6b" />

Here is the output from the terminal:
------------------------------------
(simba) carolineibanez@Carolines-MacBook-Air ~ % simba
['Pastel1', 'Pastel2', 'Paired', 'Accent', 'Dark2', 'Set1', 'Set2', 'Set3', 'tab10', 'tab20', 'magma', 'jet', 'inferno', 'plasma', 'viridis', 'gnuplot2', 'RdBu', 'winter', 'coolwarm']
SimBA environment variables: {'PRINT_EMOJIS': True, 'UNSUPERVISED_INTERFACE': False, 'NUMBA_PRECOMPILE': False, 'CUML': False}. Load time: 26.8949s
warning||SimBA is not extensively tested beyond python 3.6. You are using python 3.10. If you encounter errors in python>3.6, please report them on GitHub or Gitter (links in the help toolbar) and we will work together to fix the issues!
warning||SimBA could not find a FFMPEG installation on computer (as evaluated by "ffmpeg" returning None). SimBA works best with FFMPEG and it is recommended to install it on your computer
2025-09-26 15:40:59.363 python3.10[74843:32654796] The class 'NSOpenPanel' overrides the method identifier.  This method is implemented by class 'NSWindow'
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Users/carolineibanez/anaconda3/envs/simba/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/Users/carolineibanez/anaconda3/envs/simba/lib/python3.10/site-packages/simba/ui/import_pose_frame.py", line 371, in <lambda>
    self.run_btn = Button(self.import_frm, text="IMPORT SLEAP H5", font=Formats.FONT_REGULAR.value, fg="blue", command=lambda: self.__multi_animal_run_call(pose_estimation_tool=data_type_choice,
  File "/Users/carolineibanez/anaconda3/envs/simba/lib/python3.10/site-packages/simba/ui/import_pose_frame.py", line 227, in __multi_animal_run_call
    data_importer.run()
  File "/Users/carolineibanez/anaconda3/envs/simba/lib/python3.10/site-packages/simba/pose_importers/sleap_h5_importer.py", line 132, in run
    self.out_df = self.insert_multi_idx_columns(df=self.data_df.fillna(0))
AttributeError: 'SLEAPImporterH5' object has no attribute 'insert_multi_idx_columns'
---------------------------------------------------

**Desktop (please complete the following information):**
 - OS: [macOS Sequoia 15.6.1]
 - Python Version [3.10.18]
 - Are you using anaconda? Yes

**Comment by sronilsson** [comment]
Thanks @sara-xinyue-liang - I really appreciate it, should be a bug, let me fix and get back to you.

**Comment by sronilsson** [comment]
@sara-xinyue-liang - how doe sit look like if you update SimBA to version 3.8.9?

**Comment by sara-xinyue-liang** [comment]
Hi, Thank you for your response! After updating simba to 3.8.9 (and to 3.9.2 now), we are able to import H5 sleap data without problem. I will let you know if we run into any other issues!
Thank you os much!

**Comment by sronilsson** [comment]
Cool thanks again for reporting @sara-xinyue-liang 🚀
